export class ImagineResponse {
    /**
    * Use returned jobid value to retrieve job status and results
    */
    'jobid': string;
    'verb': ImagineResponseVerbEnum;
    'status': ImagineResponseStatusEnum;
    'created': string;
    'updated': string;
    'prompt': string;
    'channel': string;
    'server': string;
    'maxJobs': number;
    'messageId': string;
    /**
    * Contains message generated by Midjourney reflecting current generation parameters and progress
    */
    'content': string;
    'timestamp': string;
    'code': ImagineResponseCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "jobid",
            "baseName": "jobid",
            "type": "string",
            "format": ""
        },
        {
            "name": "verb",
            "baseName": "verb",
            "type": "ImagineResponseVerbEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ImagineResponseStatusEnum",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string",
            "format": ""
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "string",
            "format": ""
        },
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "string",
            "format": ""
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string",
            "format": ""
        },
        {
            "name": "server",
            "baseName": "server",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxJobs",
            "baseName": "maxJobs",
            "type": "number",
            "format": ""
        },
        {
            "name": "messageId",
            "baseName": "messageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "ImagineResponseCodeEnum",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return ImagineResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ImagineResponseVerbEnum {
    Imagine = 'imagine'
}
export enum ImagineResponseStatusEnum {
    Started = 'started'
}
export enum ImagineResponseCodeEnum {
    NUMBER_200 = 200
}

